### ISSUE TITLE
Color error in the browser

### ISSUE THREAD

**Issue by karthigayini** [maximilianh/cellBrowser#158]
HI 

I used cellbrowser v0.7.1 in a HPC environment to create the files required to host it on our website. 
The issue here is that a warning message pops:
![image](https://user-images.githubusercontent.com/17323593/74478927-f06b7080-4e73-11ea-8436-a7b8eb452e0e.png)
 On closing the dialog box, we are able to see only black and white images. 
Additional problem here is that, the above warning **does not** pop up in my personal Mac alone, in any browser (Chrome, safari or Firefox). But everybody else's  ( tested in 8 other machines) shows up the error. 

Can you please help fix this?

**Comment by maximilianh** [comment]
Sure, we’ll get this to work, no worries.

 Is this website accessible from outside ? Is there a way I could reproduce
or look at this ?

The most mysterious part is that it’s working from your laptop but not from
other peoples’ laptops... you are all accessing the same website I assume?

**Comment by karthigayini** [comment]
Is this website accessible from outside ? Is there a way I could reproduce
or look at this ?
Sure sure. Here is the link http://www.konopkalab.org/cellbrowser/

Yes, we are all using the link given above, where the results are hosted.

**Comment by maximilianh** [comment]
Hm, weird it's all working fine for me...
E.g. http://www.konopkalab.org/cellbrowser/?ds=integrImport&meta=DFclassifications02500053794&layout=1

Hey @matthewspeir do you see any problems, when looking at this link
on your laptop?

Karthigayini, do you know if these eight other people who have
problems loading the page have anything in common in their computer
configuration? Are they all Windows machines, for example?

**Comment by maximilianh** [comment]
(Oops. I'm getting this error now on our own testing site, but not yours.)

Can I ask how you installed the cell browser?

**Comment by maximilianh** [comment]
This may be unrelated, but I am getting the same error, due to change
I made yesterday, but the change was committed only to the develop
branch and only on the github repo, it was never released or merged
into the master branch. I know it's unlikely, but did you happen to
install from the "develop" branch?

**Comment by karthigayini** [comment]
Karthigayini, do you know if these eight other people who have
problems loading the page have anything in common in their computer
configuration? Are they all Windows machines, for example?
They are all different kinds of machines with different OS, in fact- Mac, Windows, VM - in Mac, Dell, Thinkpad and a desktop. 

I, too , think this is weird. The only common thing is we used the same WiFi. 
Do you think, we would need some specific java version or color package to see the colors?

**Comment by matthewspeir** [comment]
Hmm. I don't seem to be able to replicate.

@karthigayini Can you give the exact steps taken on these other computers to trigger the errors? For example, was it immediately after you open the dataset, or did it only happen with a specific metadata field, or did you have to zoom in or select some certain set of cells?

@maximilianh Would it be helpful to have zip of the cbBuild output to see if we can replicate it on our servers?

**Comment by maximilianh** [comment]
@mattspeir you mean copy
http://www.konopkalab.org/cellbrowser/and serve the page from our web
server, to see if it has to do something with the particular combination of
web server and web browser ? Hm. We can try but it seems really unlikely,
as all the three of us can’t reproduce the problem...

**Comment by karthigayini** [comment]
@matthewspeir It is exactly after we click "open". 
I understand it is difficult to solve something we don't see, unfortunately it is true that the error pops.

**Comment by karthigayini** [comment]
So, I opened the link "http://localhost:8888" first ( without even running any cellbrowser) in a new laptop and then opened the konopkalab.org/cellbrowser link. Now the colors are seen. Did the same with another computer and works. 
I think, the the browser should have opened the localhost once to see the colors. 
I am not sure if this makes sense technically but work. 

Yet, there is a problem as not every other person who wants to browse the data would have opened the local host. 

Is there something we could do about this?

Thanks

**Comment by matthewspeir** [comment]
I was actually able to replicate this issue using FireFox.

The same error message shows up when I open the dataset in FireFox:
>internal error: cbDraw.drawDots - colorArr is not 1/2 of coords array. Got 37 color values but coordinates for 131325 cells.

And I see the following If I open the debug console:
>RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer 5 cbData.js:381:23
>>    onMetaDone http://www.konopkalab.org/cellbrowser/js/cbData.js?7b401999a4:381
>>    onDoneBinaryData http://www.konopkalab.org/cellbrowser/js/cbData.js?7b401999a4:177

**Comment by matthewspeir** [comment]
@maximilianh Can you try opening their cell browser in FireFox to see if you can replicate the issue?

**Comment by karthigayini** [comment]
Is there any update? We really need this to be up and running soon. Sorry to bother.

**Comment by maximilianh** [comment]
Hi, sorry, it slipped. I'm just looking at it again now, in the meantime,
would it be possible to share the dataset with us? Debugging is so much
easier if I have the data on disk here. You can share it with
max@soe.ucsc.edu via dropbox or google drive or better yet provide a http
link. I'd like to get the input matrix, meta data and cellbrowser.conf and
anything else in the input directory required for building, e.g. the
cluster label acronyms.

**Comment by maximilianh** [comment]
To confirm, I'd only use it for debugging and delete it afterwards.

>

**Comment by maximilianh** [comment]
And @matthewspeir, I was able to replicate the issue in Firefox. It's not related to the compression, at least I think so, as the compression header is not set on the file. I don't know what it is, if we have the source files, we could host the files on our Apache temporarily and check if it's webserver related (most likely). Once we know what it is, I can work around it on the client or we can tell @karthigayini what to do on the webserver. I'm really surprised that no one else has come across this before though...

**Comment by maximilianh** [comment]
Hey @karthigayini is there any way you could prepare a zip or tgz file of these html files or send us the input files with the cellbrowser.conf file? Sorry to bother, but you said that you needed it soon and I'm happy to help, but I think without the files (either the html directory or the input directory), it'll be a lot easier debug. For now I'm still looking at Firefox.

**Comment by karthigayini** [comment]
Hi. Sorry for the delay. Sure. I will send all the necessary files as a http link to max@soe.ucsc.edu. 
A quick note, do you also see that the error is resolved if you open the http://localhost:8888 once?

**Comment by matthewspeir** [comment]
Hi @karthigayini, "localhost" refers to your computer/server. It's not accessible from the outside. If I put the localhost address into the address bar for my computer, it's going to look for a server running on my local machine, not the cell browser instance on your servers. Even then, I tried navigating to the localhost address you shared first and I still get the error in FireFox.  

In the meantime, could your labmates use Google Chrome to access the site? It seems to work in that web browser for me, but doesn't seem to work in FireFox or Safari.

**Comment by karthigayini** [comment]
Thanks for the explanation. 
We tried in chrome and still the same error.
I am uploading the files and will send them as soon as it is done.

**Comment by karthigayini** [comment]
Yes, with the link you provided, it works now. Thanks.
